version: '3.1'

services: 
  localstack:
    image: localstack/localstack:latest
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - DEBUG=1
      - SERVICES=lambda,s3,cloudformation,sts,dynamodb,iam,sns,sqs
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    ports: 
      - '4566-4597:4566-4597'
    volumes: 
      - "${TEMPDIR:-/tmp/localstack}:/temp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock" 
    command: "aws configure set aws_access_key_id test
      &&  aws configure set aws_secret_access_key test
      && aws configure set region us-east-1"
      
  wiremock:
    image: wiremock/wiremock:2.32.0
    container_name: wiremock
    ports:
      - "8882:8080"
    volumes:
      - ./mocks/__files:/home/wiremock/__files
      - ./mocks/mappings:/home/wiremock/mappings
    command:
      - "--local-response-templating"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 256M
        reservations:
          memory: 150M