service: cron_aws

frameworkVersion: '3'

plugins:
  - serverless-localstack

provider:
  name: aws
  runtime: python3.8

custom:
  localstack:
    debug: true
    stages:
     - local
     - dev
    endpointFile: localstack_endpoints.json

functions:
  handler:
    handler: handler.hello
#