service: coronas
frameworkVersion: '3'

plugins:
  - serverless-localstack
  # - serverless-localstack-sns

custom:
  localstack:
    debug: true
    stages:
     - local
     - dev
    endpointFile: localstack_endpoints.json

provider:
  name: aws
  runtime: python3.8
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:BatchGetItem
        - dynamodb:GetItem
        - dynamodb:GetRecords
        - dynamodb:Scan
        - dynamodb:Query
        - dynamodb:GetShardIterator
        - dynamodb:DescribeStream
        - dynamodb:ListStreams
      Resource: arn:aws:dynamodb:us-east-1:*:*
      
resources:
  Resources:
    MyTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: my_table
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: internal_process_status_code
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: status_code
            KeySchema:
              - AttributeName: internal_process_status_code
                KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES


functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: handler